// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: depot.proto

package org.kiwi.proto;

public final class FloatingAverageProtos {

    private FloatingAverageProtos() {
    }
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QuoteOrBuilder extends
          // @@protoc_insertion_point(interface_extends:floatingquotes.Quote)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string value = 1;</code>
     */
    java.lang.String getValue();
    /**
     * <code>string value = 1;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>string average = 2;</code>
     */
    java.lang.String getAverage();
    /**
     * <code>string average = 2;</code>
     */
    com.google.protobuf.ByteString
    getAverageBytes();

    /**
     * <code>int64 updatedAt = 3;</code>
     */
    long getUpdatedAt();
  }
  /**
   * Protobuf type {@code floatingquotes.Quote}
   */
  public static final class Quote extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:floatingquotes.Quote)
          QuoteOrBuilder {
    // Use Quote.newBuilder() to construct.
    private Quote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Quote() {
      value_ = "";
      average_ = "";
      updatedAt_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Quote(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              average_ = s;
              break;
            }
            case 24: {

              updatedAt_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return org.kiwi.proto.FloatingAverageProtos.internal_static_floatingquotes_Quote_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return org.kiwi.proto.FloatingAverageProtos.internal_static_floatingquotes_Quote_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      org.kiwi.proto.FloatingAverageProtos.Quote.class,
                      org.kiwi.proto.FloatingAverageProtos.Quote.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 1;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 1;</code>
     */
    public com.google.protobuf.ByteString
    getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVERAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object average_;
    /**
     * <code>string average = 2;</code>
     */
    public java.lang.String getAverage() {
      java.lang.Object ref = average_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        average_ = s;
        return s;
      }
    }
    /**
     * <code>string average = 2;</code>
     */
    public com.google.protobuf.ByteString
    getAverageBytes() {
      java.lang.Object ref = average_;
      if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
        average_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATEDAT_FIELD_NUMBER = 3;
    private long updatedAt_;
    /**
     * <code>int64 updatedAt = 3;</code>
     */
    public long getUpdatedAt() {
      return updatedAt_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {
            return true;
        }
        if (isInitialized == 0) {
            return false;
        }

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_);
      }
      if (!getAverageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, average_);
      }
      if (updatedAt_ != 0L) {
        output.writeInt64(3, updatedAt_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
        if (size != -1) {
            return size;
        }

      size = 0;
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value_);
      }
      if (!getAverageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, average_);
      }
      if (updatedAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(3, updatedAt_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
          return true;
      }
      if (!(obj instanceof org.kiwi.proto.FloatingAverageProtos.Quote)) {
        return super.equals(obj);
      }
      org.kiwi.proto.FloatingAverageProtos.Quote other = (org.kiwi.proto.FloatingAverageProtos.Quote) obj;

      boolean result = true;
      result = result && getValue()
              .equals(other.getValue());
      result = result && getAverage()
              .equals(other.getAverage());
      result = result && (getUpdatedAt()
              == other.getUpdatedAt());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + AVERAGE_FIELD_NUMBER;
      hash = (53 * hash) + getAverage().hashCode();
      hash = (37 * hash) + UPDATEDAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getUpdatedAt());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.kiwi.proto.FloatingAverageProtos.Quote parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kiwi.proto.FloatingAverageProtos.Quote parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kiwi.proto.FloatingAverageProtos.Quote parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kiwi.proto.FloatingAverageProtos.Quote parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kiwi.proto.FloatingAverageProtos.Quote parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static org.kiwi.proto.FloatingAverageProtos.Quote parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.kiwi.proto.FloatingAverageProtos.Quote parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.kiwi.proto.FloatingAverageProtos.Quote parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.kiwi.proto.FloatingAverageProtos.Quote parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static org.kiwi.proto.FloatingAverageProtos.Quote parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

      public Builder newBuilderForType() {
          return newBuilder();
      }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.kiwi.proto.FloatingAverageProtos.Quote prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code floatingquotes.Quote}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:floatingquotes.Quote)
            org.kiwi.proto.FloatingAverageProtos.QuoteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return org.kiwi.proto.FloatingAverageProtos.internal_static_floatingquotes_Quote_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return org.kiwi.proto.FloatingAverageProtos.internal_static_floatingquotes_Quote_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        org.kiwi.proto.FloatingAverageProtos.Quote.class,
                        org.kiwi.proto.FloatingAverageProtos.Quote.Builder.class);
      }

      // Construct using org.kiwi.proto.FloatingAverageProtos.Quote.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = "";

        average_ = "";

        updatedAt_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return org.kiwi.proto.FloatingAverageProtos.internal_static_floatingquotes_Quote_descriptor;
      }

      public org.kiwi.proto.FloatingAverageProtos.Quote getDefaultInstanceForType() {
        return org.kiwi.proto.FloatingAverageProtos.Quote.getDefaultInstance();
      }

      public org.kiwi.proto.FloatingAverageProtos.Quote build() {
        org.kiwi.proto.FloatingAverageProtos.Quote result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.kiwi.proto.FloatingAverageProtos.Quote buildPartial() {
        org.kiwi.proto.FloatingAverageProtos.Quote result = new org.kiwi.proto.FloatingAverageProtos.Quote(this);
        result.value_ = value_;
        result.average_ = average_;
        result.updatedAt_ = updatedAt_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.kiwi.proto.FloatingAverageProtos.Quote) {
            return mergeFrom((org.kiwi.proto.FloatingAverageProtos.Quote) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.kiwi.proto.FloatingAverageProtos.Quote other) {
          if (other == org.kiwi.proto.FloatingAverageProtos.Quote.getDefaultInstance()) {
              return this;
          }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        if (!other.getAverage().isEmpty()) {
          average_ = other.average_;
          onChanged();
        }
        if (other.getUpdatedAt() != 0L) {
          setUpdatedAt(other.getUpdatedAt());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        org.kiwi.proto.FloatingAverageProtos.Quote parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.kiwi.proto.FloatingAverageProtos.Quote) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 1;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       */
      public com.google.protobuf.ByteString
      getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder setValue(
              java.lang.String value) {
        if (value == null) {
            throw new NullPointerException();
        }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder clearValue() {

          value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder setValueBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
            throw new NullPointerException();
        }
          checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object average_ = "";
      /**
       * <code>string average = 2;</code>
       */
      public java.lang.String getAverage() {
        java.lang.Object ref = average_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          average_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string average = 2;</code>
       */
      public com.google.protobuf.ByteString
      getAverageBytes() {
        java.lang.Object ref = average_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
          average_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string average = 2;</code>
       */
      public Builder setAverage(
              java.lang.String value) {
        if (value == null) {
            throw new NullPointerException();
        }
  
        average_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string average = 2;</code>
       */
      public Builder clearAverage() {

          average_ = getDefaultInstance().getAverage();
        onChanged();
        return this;
      }
      /**
       * <code>string average = 2;</code>
       */
      public Builder setAverageBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
            throw new NullPointerException();
        }
          checkByteStringIsUtf8(value);
        
        average_ = value;
        onChanged();
        return this;
      }

        private long updatedAt_;
      /**
       * <code>int64 updatedAt = 3;</code>
       */
      public long getUpdatedAt() {
        return updatedAt_;
      }
      /**
       * <code>int64 updatedAt = 3;</code>
       */
      public Builder setUpdatedAt(long value) {

          updatedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 updatedAt = 3;</code>
       */
      public Builder clearUpdatedAt() {

          updatedAt_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:floatingquotes.Quote)
    }

    // @@protoc_insertion_point(class_scope:floatingquotes.Quote)
    private static final org.kiwi.proto.FloatingAverageProtos.Quote DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.kiwi.proto.FloatingAverageProtos.Quote();
    }

    public static org.kiwi.proto.FloatingAverageProtos.Quote getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Quote>
            PARSER = new com.google.protobuf.AbstractParser<Quote>() {
      public Quote parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
          return new Quote(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Quote> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Quote> getParserForType() {
      return PARSER;
    }

    public org.kiwi.proto.FloatingAverageProtos.Quote getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FloatingAverageOrBuilder extends
          // @@protoc_insertion_point(interface_extends:floatingquotes.FloatingAverage)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
    getIdBytes();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
    getNameBytes();

    /**
     * <code>string symbol = 3;</code>
     */
    java.lang.String getSymbol();
    /**
     * <code>string symbol = 3;</code>
     */
    com.google.protobuf.ByteString
    getSymbolBytes();

    /**
     * <code>int32 maxDaysCap = 4;</code>
     */
    int getMaxDaysCap();

      /**
       * <code>repeated .floatingquotes.Quote quotes = 5;</code>
     */
      java.util.List<org.kiwi.proto.FloatingAverageProtos.Quote>
      getQuotesList();
    /**
     * <code>repeated .floatingquotes.Quote quotes = 5;</code>
     */
    org.kiwi.proto.FloatingAverageProtos.Quote getQuotes(int index);
    /**
     * <code>repeated .floatingquotes.Quote quotes = 5;</code>
     */
    int getQuotesCount();
    /**
     * <code>repeated .floatingquotes.Quote quotes = 5;</code>
     */
    java.util.List<? extends org.kiwi.proto.FloatingAverageProtos.QuoteOrBuilder>
    getQuotesOrBuilderList();
    /**
     * <code>repeated .floatingquotes.Quote quotes = 5;</code>
     */
    org.kiwi.proto.FloatingAverageProtos.QuoteOrBuilder getQuotesOrBuilder(
            int index);

    /**
     * <code>string deviationThreshold = 6;</code>
     */
    java.lang.String getDeviationThreshold();
    /**
     * <code>string deviationThreshold = 6;</code>
     */
    com.google.protobuf.ByteString
    getDeviationThresholdBytes();

    /**
     * <code>string latestAverage = 7;</code>
     */
    java.lang.String getLatestAverage();

    /**
     * <code>string latestAverage = 7;</code>
     */
    com.google.protobuf.ByteString
    getLatestAverageBytes();

    /**
     * <code>string latestQuoteValue = 8;</code>
     */
    java.lang.String getLatestQuoteValue();

    /**
     * <code>string latestQuoteValue = 8;</code>
     */
    com.google.protobuf.ByteString
    getLatestQuoteValueBytes();

    /**
     * <code>int64 closingDate = 9;</code>
     */
    long getClosingDate();

    /**
     * <code>.floatingquotes.FloatingAverage.AlertState alertState = 10;</code>
     */
    int getAlertStateValue();

    /**
     * <code>.floatingquotes.FloatingAverage.AlertState alertState = 10;</code>
     */
    org.kiwi.proto.FloatingAverageProtos.FloatingAverage.AlertState getAlertState();
  }
  /**
   * Protobuf type {@code floatingquotes.FloatingAverage}
   */
  public static final class FloatingAverage extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:floatingquotes.FloatingAverage)
          FloatingAverageOrBuilder {
    // Use FloatingAverage.newBuilder() to construct.
    private FloatingAverage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FloatingAverage() {
      id_ = "";
      name_ = "";
      symbol_ = "";
      maxDaysCap_ = 0;
      quotes_ = java.util.Collections.emptyList();
      deviationThreshold_ = "";
      latestAverage_ = "";
      latestQuoteValue_ = "";
      closingDate_ = 0L;
      alertState_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FloatingAverage(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              symbol_ = s;
              break;
            }
              case 32: {

                  maxDaysCap_ = input.readInt32();
                  break;
              }
              case 42: {
                  if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                quotes_ = new java.util.ArrayList<org.kiwi.proto.FloatingAverageProtos.Quote>();
                      mutable_bitField0_ |= 0x00000010;
                  }
                quotes_.add(
                        input.readMessage(org.kiwi.proto.FloatingAverageProtos.Quote.parser(), extensionRegistry));
                break;
              }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              deviationThreshold_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              latestAverage_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              latestQuoteValue_ = s;
              break;
            }
            case 72: {

              closingDate_ = input.readInt64();
              break;
            }
            case 80: {
              int rawValue = input.readEnum();

              alertState_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
          if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          quotes_ = java.util.Collections.unmodifiableList(quotes_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return org.kiwi.proto.FloatingAverageProtos.internal_static_floatingquotes_FloatingAverage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return org.kiwi.proto.FloatingAverageProtos.internal_static_floatingquotes_FloatingAverage_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      org.kiwi.proto.FloatingAverageProtos.FloatingAverage.class,
                      org.kiwi.proto.FloatingAverageProtos.FloatingAverage.Builder.class);
    }

    /**
     * Protobuf enum {@code floatingquotes.FloatingAverage.AlertState}
     */
    public enum AlertState
            implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NONE = 0;</code>
       */
      NONE(0),
      /**
       * <code>BUY = 1;</code>
       */
      BUY(1),
      /**
       * <code>SELL = 2;</code>
       */
      SELL(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NONE = 0;</code>
       */
      public static final int NONE_VALUE = 0;
      /**
       * <code>BUY = 1;</code>
       */
      public static final int BUY_VALUE = 1;
      /**
       * <code>SELL = 2;</code>
       */
      public static final int SELL_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
                  "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static AlertState valueOf(int value) {
        return forNumber(value);
      }

      public static AlertState forNumber(int value) {
        switch (value) {
          case 0:
            return NONE;
          case 1:
            return BUY;
          case 2:
            return SELL;
          default:
            return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<AlertState>
      internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
              AlertState> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<AlertState>() {
                  public AlertState findValueByNumber(int number) {
                      return AlertState.forNumber(number);
                  }
              };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
        return org.kiwi.proto.FloatingAverageProtos.FloatingAverage.getDescriptor().getEnumTypes().get(0);
      }

      private static final AlertState[] VALUES = values();

      public static AlertState valueOf(
              com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
                  "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private AlertState(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:floatingquotes.FloatingAverage.AlertState)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
    getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
    getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SYMBOL_FIELD_NUMBER = 3;
    private volatile java.lang.Object symbol_;
    /**
     * <code>string symbol = 3;</code>
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      }
    }
    /**
     * <code>string symbol = 3;</code>
     */
    public com.google.protobuf.ByteString
    getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

      public static final int MAXDAYSCAP_FIELD_NUMBER = 4;
      private int maxDaysCap_;

      /**
       * <code>int32 maxDaysCap = 4;</code>
       */
      public int getMaxDaysCap() {
          return maxDaysCap_;
      }

      public static final int QUOTES_FIELD_NUMBER = 5;
    private java.util.List<org.kiwi.proto.FloatingAverageProtos.Quote> quotes_;

      /**
       * <code>repeated .floatingquotes.Quote quotes = 5;</code>
     */
    public java.util.List<org.kiwi.proto.FloatingAverageProtos.Quote> getQuotesList() {
      return quotes_;
    }

      /**
       * <code>repeated .floatingquotes.Quote quotes = 5;</code>
       */
      public java.util.List<? extends org.kiwi.proto.FloatingAverageProtos.QuoteOrBuilder>
      getQuotesOrBuilderList() {
        return quotes_;
      }

      /**
       * <code>repeated .floatingquotes.Quote quotes = 5;</code>
     */
    public int getQuotesCount() {
      return quotes_.size();
    }

      /**
       * <code>repeated .floatingquotes.Quote quotes = 5;</code>
     */
    public org.kiwi.proto.FloatingAverageProtos.Quote getQuotes(int index) {
      return quotes_.get(index);
    }

      /**
       * <code>repeated .floatingquotes.Quote quotes = 5;</code>
     */
    public org.kiwi.proto.FloatingAverageProtos.QuoteOrBuilder getQuotesOrBuilder(
            int index) {
      return quotes_.get(index);
    }

    public static final int DEVIATIONTHRESHOLD_FIELD_NUMBER = 6;
    private volatile java.lang.Object deviationThreshold_;

    /**
     * <code>string deviationThreshold = 6;</code>
     */
    public java.lang.String getDeviationThreshold() {
      java.lang.Object ref = deviationThreshold_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviationThreshold_ = s;
        return s;
      }
    }

    /**
     * <code>string deviationThreshold = 6;</code>
     */
    public com.google.protobuf.ByteString
    getDeviationThresholdBytes() {
      java.lang.Object ref = deviationThreshold_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        deviationThreshold_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATESTAVERAGE_FIELD_NUMBER = 7;
    private volatile java.lang.Object latestAverage_;

    /**
     * <code>string latestAverage = 7;</code>
     */
    public java.lang.String getLatestAverage() {
      java.lang.Object ref = latestAverage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        latestAverage_ = s;
        return s;
      }
    }

    /**
     * <code>string latestAverage = 7;</code>
     */
    public com.google.protobuf.ByteString
    getLatestAverageBytes() {
      java.lang.Object ref = latestAverage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        latestAverage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATESTQUOTEVALUE_FIELD_NUMBER = 8;
    private volatile java.lang.Object latestQuoteValue_;

    /**
     * <code>string latestQuoteValue = 8;</code>
     */
    public java.lang.String getLatestQuoteValue() {
      java.lang.Object ref = latestQuoteValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        latestQuoteValue_ = s;
        return s;
      }
    }

    /**
     * <code>string latestQuoteValue = 8;</code>
     */
    public com.google.protobuf.ByteString
    getLatestQuoteValueBytes() {
      java.lang.Object ref = latestQuoteValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        latestQuoteValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLOSINGDATE_FIELD_NUMBER = 9;
    private long closingDate_;

    /**
     * <code>int64 closingDate = 9;</code>
     */
    public long getClosingDate() {
      return closingDate_;
    }

    public static final int ALERTSTATE_FIELD_NUMBER = 10;
      private int alertState_;

    /**
     * <code>.floatingquotes.FloatingAverage.AlertState alertState = 10;</code>
     */
    public int getAlertStateValue() {
      return alertState_;
    }

    /**
     * <code>.floatingquotes.FloatingAverage.AlertState alertState = 10;</code>
     */
    public org.kiwi.proto.FloatingAverageProtos.FloatingAverage.AlertState getAlertState() {
      org.kiwi.proto.FloatingAverageProtos.FloatingAverage.AlertState result = org.kiwi.proto.FloatingAverageProtos.FloatingAverage.AlertState.valueOf(alertState_);
      return result == null ? org.kiwi.proto.FloatingAverageProtos.FloatingAverage.AlertState.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {
            return true;
        }
        if (isInitialized == 0) {
            return false;
        }

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getSymbolBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, symbol_);
      }
      if (maxDaysCap_ != 0) {
        output.writeInt32(4, maxDaysCap_);
      }
      for (int i = 0; i < quotes_.size(); i++) {
        output.writeMessage(5, quotes_.get(i));
      }
      if (!getDeviationThresholdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, deviationThreshold_);
      }
      if (!getLatestAverageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, latestAverage_);
      }
      if (!getLatestQuoteValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, latestQuoteValue_);
      }
      if (closingDate_ != 0L) {
        output.writeInt64(9, closingDate_);
      }
      if (alertState_ != org.kiwi.proto.FloatingAverageProtos.FloatingAverage.AlertState.NONE.getNumber()) {
        output.writeEnum(10, alertState_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) {
        return size;
          }

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getSymbolBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, symbol_);
      }
      if (maxDaysCap_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(4, maxDaysCap_);
      }
      for (int i = 0; i < quotes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(5, quotes_.get(i));
      }
      if (!getDeviationThresholdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, deviationThreshold_);
      }
      if (!getLatestAverageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, latestAverage_);
      }
      if (!getLatestQuoteValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, latestQuoteValue_);
      }
      if (closingDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(9, closingDate_);
      }
      if (alertState_ != org.kiwi.proto.FloatingAverageProtos.FloatingAverage.AlertState.NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
                .computeEnumSize(10, alertState_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.kiwi.proto.FloatingAverageProtos.FloatingAverage)) {
        return super.equals(obj);
      }
      org.kiwi.proto.FloatingAverageProtos.FloatingAverage other = (org.kiwi.proto.FloatingAverageProtos.FloatingAverage) obj;

        boolean result = true;
      result = result && getId()
              .equals(other.getId());
      result = result && getName()
              .equals(other.getName());
      result = result && getSymbol()
              .equals(other.getSymbol());
        result = result && (getMaxDaysCap()
                == other.getMaxDaysCap());
      result = result && getQuotesList()
              .equals(other.getQuotesList());
      result = result && getDeviationThreshold()
              .equals(other.getDeviationThreshold());
      result = result && getLatestAverage()
              .equals(other.getLatestAverage());
      result = result && getLatestQuoteValue()
              .equals(other.getLatestQuoteValue());
      result = result && (getClosingDate()
              == other.getClosingDate());
      result = result && alertState_ == other.alertState_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + getSymbol().hashCode();
        hash = (37 * hash) + MAXDAYSCAP_FIELD_NUMBER;
      hash = (53 * hash) + getMaxDaysCap();
      if (getQuotesCount() > 0) {
        hash = (37 * hash) + QUOTES_FIELD_NUMBER;
        hash = (53 * hash) + getQuotesList().hashCode();
      }
      hash = (37 * hash) + DEVIATIONTHRESHOLD_FIELD_NUMBER;
      hash = (53 * hash) + getDeviationThreshold().hashCode();
      hash = (37 * hash) + LATESTAVERAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLatestAverage().hashCode();
      hash = (37 * hash) + LATESTQUOTEVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getLatestQuoteValue().hashCode();
      hash = (37 * hash) + CLOSINGDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getClosingDate());
      hash = (37 * hash) + ALERTSTATE_FIELD_NUMBER;
      hash = (53 * hash) + alertState_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.kiwi.proto.FloatingAverageProtos.FloatingAverage parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kiwi.proto.FloatingAverageProtos.FloatingAverage parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kiwi.proto.FloatingAverageProtos.FloatingAverage parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kiwi.proto.FloatingAverageProtos.FloatingAverage parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kiwi.proto.FloatingAverageProtos.FloatingAverage parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static org.kiwi.proto.FloatingAverageProtos.FloatingAverage parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.kiwi.proto.FloatingAverageProtos.FloatingAverage parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.kiwi.proto.FloatingAverageProtos.FloatingAverage parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.kiwi.proto.FloatingAverageProtos.FloatingAverage parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static org.kiwi.proto.FloatingAverageProtos.FloatingAverage parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.kiwi.proto.FloatingAverageProtos.FloatingAverage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code floatingquotes.FloatingAverage}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:floatingquotes.FloatingAverage)
            org.kiwi.proto.FloatingAverageProtos.FloatingAverageOrBuilder {

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kiwi.proto.FloatingAverageProtos.internal_static_floatingquotes_FloatingAverage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return org.kiwi.proto.FloatingAverageProtos.internal_static_floatingquotes_FloatingAverage_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        org.kiwi.proto.FloatingAverageProtos.FloatingAverage.class, org.kiwi.proto.FloatingAverageProtos.FloatingAverage.Builder.class);
      }

      // Construct using org.kiwi.proto.FloatingAverageProtos.FloatingAverage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getQuotesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
          id_ = "";

        name_ = "";

        symbol_ = "";

        maxDaysCap_ = 0;

        if (quotesBuilder_ == null) {
          quotes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          quotesBuilder_.clear();
        }
        deviationThreshold_ = "";

        latestAverage_ = "";

        latestQuoteValue_ = "";

        closingDate_ = 0L;

        alertState_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return org.kiwi.proto.FloatingAverageProtos.internal_static_floatingquotes_FloatingAverage_descriptor;
      }

      public org.kiwi.proto.FloatingAverageProtos.FloatingAverage getDefaultInstanceForType() {
        return org.kiwi.proto.FloatingAverageProtos.FloatingAverage.getDefaultInstance();
      }

      public org.kiwi.proto.FloatingAverageProtos.FloatingAverage build() {
        org.kiwi.proto.FloatingAverageProtos.FloatingAverage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.kiwi.proto.FloatingAverageProtos.FloatingAverage buildPartial() {
          org.kiwi.proto.FloatingAverageProtos.FloatingAverage result = new org.kiwi.proto.FloatingAverageProtos.FloatingAverage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        result.symbol_ = symbol_;
          result.maxDaysCap_ = maxDaysCap_;
        if (quotesBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            quotes_ = java.util.Collections.unmodifiableList(quotes_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.quotes_ = quotes_;
        } else {
          result.quotes_ = quotesBuilder_.build();
        }
        result.deviationThreshold_ = deviationThreshold_;
        result.latestAverage_ = latestAverage_;
        result.latestQuoteValue_ = latestQuoteValue_;
        result.closingDate_ = closingDate_;
        result.alertState_ = alertState_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.kiwi.proto.FloatingAverageProtos.FloatingAverage) {
            return mergeFrom((org.kiwi.proto.FloatingAverageProtos.FloatingAverage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.kiwi.proto.FloatingAverageProtos.FloatingAverage other) {
          if (other == org.kiwi.proto.FloatingAverageProtos.FloatingAverage.getDefaultInstance()) {
              return this;
          }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getSymbol().isEmpty()) {
          symbol_ = other.symbol_;
            onChanged();
        }
          if (other.getMaxDaysCap() != 0) {
            setMaxDaysCap(other.getMaxDaysCap());
        }
        if (quotesBuilder_ == null) {
          if (!other.quotes_.isEmpty()) {
            if (quotes_.isEmpty()) {
              quotes_ = other.quotes_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureQuotesIsMutable();
              quotes_.addAll(other.quotes_);
            }
            onChanged();
          }
        } else {
          if (!other.quotes_.isEmpty()) {
            if (quotesBuilder_.isEmpty()) {
              quotesBuilder_.dispose();
              quotesBuilder_ = null;
              quotes_ = other.quotes_;
                bitField0_ = (bitField0_ & ~0x00000010);
                quotesBuilder_ =
                        com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                getQuotesFieldBuilder() : null;
            } else {
              quotesBuilder_.addAllMessages(other.quotes_);
            }
          }
        }
        if (!other.getDeviationThreshold().isEmpty()) {
          deviationThreshold_ = other.deviationThreshold_;
          onChanged();
        }
        if (!other.getLatestAverage().isEmpty()) {
          latestAverage_ = other.latestAverage_;
          onChanged();
        }
        if (!other.getLatestQuoteValue().isEmpty()) {
          latestQuoteValue_ = other.latestQuoteValue_;
          onChanged();
        }
        if (other.getClosingDate() != 0L) {
          setClosingDate(other.getClosingDate());
        }
        if (other.alertState_ != 0) {
          setAlertStateValue(other.getAlertStateValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        org.kiwi.proto.FloatingAverageProtos.FloatingAverage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.kiwi.proto.FloatingAverageProtos.FloatingAverage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
      getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {

        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
      getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object symbol_ = "";
      /**
       * <code>string symbol = 3;</code>
       */
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          symbol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string symbol = 3;</code>
       */
      public com.google.protobuf.ByteString
      getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string symbol = 3;</code>
       */
      public Builder setSymbol(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
  }
  
        symbol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 3;</code>
       */
      public Builder clearSymbol() {

        symbol_ = getDefaultInstance().getSymbol();
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 3;</code>
       */
      public Builder setSymbolBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        symbol_ = value;
        onChanged();
          return this;
      }

        private int maxDaysCap_;

        /**
         * <code>int32 maxDaysCap = 4;</code>
         */
        public int getMaxDaysCap() {
            return maxDaysCap_;
        }

        /**
         * <code>int32 maxDaysCap = 4;</code>
         */
        public Builder setMaxDaysCap(int value) {

            maxDaysCap_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 maxDaysCap = 4;</code>
         */
        public Builder clearMaxDaysCap() {

          maxDaysCap_ = 0;
          onChanged();
        return this;
      }

      private java.util.List<org.kiwi.proto.FloatingAverageProtos.Quote> quotes_ =
              java.util.Collections.emptyList();

      private void ensureQuotesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          quotes_ = new java.util.ArrayList<org.kiwi.proto.FloatingAverageProtos.Quote>(quotes_);
          bitField0_ |= 0x00000010;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              org.kiwi.proto.FloatingAverageProtos.Quote, org.kiwi.proto.FloatingAverageProtos.Quote.Builder, org.kiwi.proto.FloatingAverageProtos.QuoteOrBuilder> quotesBuilder_;

      /**
       * <code>repeated .floatingquotes.Quote quotes = 5;</code>
       */
      public java.util.List<org.kiwi.proto.FloatingAverageProtos.Quote> getQuotesList() {
        if (quotesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(quotes_);
        } else {
          return quotesBuilder_.getMessageList();
        }
      }

      /**
       * <code>repeated .floatingquotes.Quote quotes = 5;</code>
       */
      public int getQuotesCount() {
        if (quotesBuilder_ == null) {
          return quotes_.size();
        } else {
          return quotesBuilder_.getCount();
        }
      }

      /**
       * <code>repeated .floatingquotes.Quote quotes = 5;</code>
       */
      public org.kiwi.proto.FloatingAverageProtos.Quote getQuotes(int index) {
        if (quotesBuilder_ == null) {
          return quotes_.get(index);
        } else {
          return quotesBuilder_.getMessage(index);
        }
      }

        /**
         * <code>repeated .floatingquotes.Quote quotes = 5;</code>
         */
        public Builder setQuotes(
                int index, org.kiwi.proto.FloatingAverageProtos.Quote value) {
        if (quotesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuotesIsMutable();
          quotes_.set(index, value);
          onChanged();
        } else {
          quotesBuilder_.setMessage(index, value);
        }
          return this;
      }

        /**
         * <code>repeated .floatingquotes.Quote quotes = 5;</code>
         */
        public Builder setQuotes(
                int index, org.kiwi.proto.FloatingAverageProtos.Quote.Builder builderForValue) {
        if (quotesBuilder_ == null) {
          ensureQuotesIsMutable();
          quotes_.set(index, builderForValue.build());
          onChanged();
        } else {
          quotesBuilder_.setMessage(index, builderForValue.build());
        }
          return this;
        }

      /**
       * <code>repeated .floatingquotes.Quote quotes = 5;</code>
       */
      public Builder addQuotes(org.kiwi.proto.FloatingAverageProtos.Quote value) {
        if (quotesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuotesIsMutable();
          quotes_.add(value);
          onChanged();
        } else {
          quotesBuilder_.addMessage(value);
        }
          return this;
      }

        /**
         * <code>repeated .floatingquotes.Quote quotes = 5;</code>
         */
        public Builder addQuotes(
                int index, org.kiwi.proto.FloatingAverageProtos.Quote value) {
        if (quotesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuotesIsMutable();
          quotes_.add(index, value);
          onChanged();
        } else {
          quotesBuilder_.addMessage(index, value);
        }
          return this;
      }

        /**
         * <code>repeated .floatingquotes.Quote quotes = 5;</code>
         */
        public Builder addQuotes(
                org.kiwi.proto.FloatingAverageProtos.Quote.Builder builderForValue) {
        if (quotesBuilder_ == null) {
          ensureQuotesIsMutable();
          quotes_.add(builderForValue.build());
          onChanged();
        } else {
          quotesBuilder_.addMessage(builderForValue.build());
        }
          return this;
      }

        /**
         * <code>repeated .floatingquotes.Quote quotes = 5;</code>
         */
        public Builder addQuotes(
                int index, org.kiwi.proto.FloatingAverageProtos.Quote.Builder builderForValue) {
        if (quotesBuilder_ == null) {
          ensureQuotesIsMutable();
          quotes_.add(index, builderForValue.build());
          onChanged();
        } else {
          quotesBuilder_.addMessage(index, builderForValue.build());
        }
            return this;
        }

        /**
         * <code>repeated .floatingquotes.Quote quotes = 5;</code>
         */
        public Builder addAllQuotes(
                java.lang.Iterable<? extends org.kiwi.proto.FloatingAverageProtos.Quote> values) {
        if (quotesBuilder_ == null) {
          ensureQuotesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
                  values, quotes_);
          onChanged();
        } else {
          quotesBuilder_.addAllMessages(values);
        }
          return this;
        }

      /**
       * <code>repeated .floatingquotes.Quote quotes = 5;</code>
       */
      public Builder clearQuotes() {
        if (quotesBuilder_ == null) {
          quotes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          quotesBuilder_.clear();
        }
        return this;
      }

      /**
       * <code>repeated .floatingquotes.Quote quotes = 5;</code>
       */
      public Builder removeQuotes(int index) {
        if (quotesBuilder_ == null) {
          ensureQuotesIsMutable();
          quotes_.remove(index);
          onChanged();
        } else {
          quotesBuilder_.remove(index);
        }
        return this;
      }

      /**
       * <code>repeated .floatingquotes.Quote quotes = 5;</code>
       */
      public org.kiwi.proto.FloatingAverageProtos.Quote.Builder getQuotesBuilder(
              int index) {
        return getQuotesFieldBuilder().getBuilder(index);
      }

      /**
       * <code>repeated .floatingquotes.Quote quotes = 5;</code>
       */
      public org.kiwi.proto.FloatingAverageProtos.QuoteOrBuilder getQuotesOrBuilder(
              int index) {
        if (quotesBuilder_ == null) {
          return quotes_.get(index);
        } else {
          return quotesBuilder_.getMessageOrBuilder(index);
        }
      }

        /**
         * <code>repeated .floatingquotes.Quote quotes = 5;</code>
         */
        public java.util.List<? extends org.kiwi.proto.FloatingAverageProtos.QuoteOrBuilder>
           getQuotesOrBuilderList() {
        if (quotesBuilder_ != null) {
          return quotesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(quotes_);
        }
        }

      /**
       * <code>repeated .floatingquotes.Quote quotes = 5;</code>
       */
      public org.kiwi.proto.FloatingAverageProtos.Quote.Builder addQuotesBuilder() {
          return getQuotesFieldBuilder().addBuilder(
                  org.kiwi.proto.FloatingAverageProtos.Quote.getDefaultInstance());
      }

      /**
       * <code>repeated .floatingquotes.Quote quotes = 5;</code>
       */
      public org.kiwi.proto.FloatingAverageProtos.Quote.Builder addQuotesBuilder(
              int index) {
          return getQuotesFieldBuilder().addBuilder(
                  index, org.kiwi.proto.FloatingAverageProtos.Quote.getDefaultInstance());
      }

        /**
         * <code>repeated .floatingquotes.Quote quotes = 5;</code>
         */
        public java.util.List<org.kiwi.proto.FloatingAverageProtos.Quote.Builder>
        getQuotesBuilderList() {
          return getQuotesFieldBuilder().getBuilderList();
        }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              org.kiwi.proto.FloatingAverageProtos.Quote, org.kiwi.proto.FloatingAverageProtos.Quote.Builder, org.kiwi.proto.FloatingAverageProtos.QuoteOrBuilder>
      getQuotesFieldBuilder() {
        if (quotesBuilder_ == null) {
          quotesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                  org.kiwi.proto.FloatingAverageProtos.Quote, org.kiwi.proto.FloatingAverageProtos.Quote.Builder, org.kiwi.proto.FloatingAverageProtos.QuoteOrBuilder>(
                  quotes_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          quotes_ = null;
        }
        return quotesBuilder_;
      }

      private java.lang.Object deviationThreshold_ = "";

      /**
       * <code>string deviationThreshold = 6;</code>
       */
      public java.lang.String getDeviationThreshold() {
        java.lang.Object ref = deviationThreshold_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviationThreshold_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string deviationThreshold = 6;</code>
         */
        public com.google.protobuf.ByteString
        getDeviationThresholdBytes() {
          java.lang.Object ref = deviationThreshold_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
              deviationThreshold_ = b;
              return b;
            } else {
              return (com.google.protobuf.ByteString) ref;
            }
        }

      /**
       * <code>string deviationThreshold = 6;</code>
       */
      public Builder setDeviationThreshold(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        deviationThreshold_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string deviationThreshold = 6;</code>
       */
      public Builder clearDeviationThreshold() {

        deviationThreshold_ = getDefaultInstance().getDeviationThreshold();
        onChanged();
        return this;
      }

      /**
       * <code>string deviationThreshold = 6;</code>
       */
      public Builder setDeviationThresholdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
              throw new NullPointerException();
            }
        checkByteStringIsUtf8(value);

        deviationThreshold_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object latestAverage_ = "";

      /**
       * <code>string latestAverage = 7;</code>
       */
      public java.lang.String getLatestAverage() {
        java.lang.Object ref = latestAverage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          latestAverage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string latestAverage = 7;</code>
       */
      public com.google.protobuf.ByteString
      getLatestAverageBytes() {
        java.lang.Object ref = latestAverage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          latestAverage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string latestAverage = 7;</code>
       */
      public Builder setLatestAverage(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        latestAverage_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string latestAverage = 7;</code>
       */
      public Builder clearLatestAverage() {

        latestAverage_ = getDefaultInstance().getLatestAverage();
        onChanged();
        return this;
      }

      /**
       * <code>string latestAverage = 7;</code>
       */
      public Builder setLatestAverageBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        latestAverage_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object latestQuoteValue_ = "";

      /**
       * <code>string latestQuoteValue = 8;</code>
       */
      public java.lang.String getLatestQuoteValue() {
        java.lang.Object ref = latestQuoteValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          latestQuoteValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string latestQuoteValue = 8;</code>
       */
      public com.google.protobuf.ByteString
      getLatestQuoteValueBytes() {
        java.lang.Object ref = latestQuoteValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          latestQuoteValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string latestQuoteValue = 8;</code>
       */
      public Builder setLatestQuoteValue(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        latestQuoteValue_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string latestQuoteValue = 8;</code>
       */
      public Builder clearLatestQuoteValue() {

        latestQuoteValue_ = getDefaultInstance().getLatestQuoteValue();
        onChanged();
        return this;
      }

      /**
       * <code>string latestQuoteValue = 8;</code>
       */
      public Builder setLatestQuoteValueBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        latestQuoteValue_ = value;
        onChanged();
            return this;
        }

        private long closingDate_ ;
      /**
       * <code>int64 closingDate = 9;</code>
       */
      public long getClosingDate() {
        return closingDate_;
      }

      /**
       * <code>int64 closingDate = 9;</code>
       */
      public Builder setClosingDate(long value) {

        closingDate_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int64 closingDate = 9;</code>
       */
      public Builder clearClosingDate() {

        closingDate_ = 0L;
        onChanged();
        return this;
      }

        private int alertState_ = 0;
      /**
       * <code>.floatingquotes.FloatingAverage.AlertState alertState = 10;</code>
       */
      public int getAlertStateValue() {
          return alertState_;
      }

        /**
         * <code>.floatingquotes.FloatingAverage.AlertState alertState = 10;</code>
       */
      public Builder setAlertStateValue(int value) {
        alertState_ = value;
        onChanged();
          return this;
      }

        /**
         * <code>.floatingquotes.FloatingAverage.AlertState alertState = 10;</code>
         */
        public org.kiwi.proto.FloatingAverageProtos.FloatingAverage.AlertState getAlertState() {
          org.kiwi.proto.FloatingAverageProtos.FloatingAverage.AlertState result = org.kiwi.proto.FloatingAverageProtos.FloatingAverage.AlertState.valueOf(alertState_);
          return result == null ? org.kiwi.proto.FloatingAverageProtos.FloatingAverage.AlertState.UNRECOGNIZED : result;
        }

      /**
       * <code>.floatingquotes.FloatingAverage.AlertState alertState = 10;</code>
       */
      public Builder setAlertState(org.kiwi.proto.FloatingAverageProtos.FloatingAverage.AlertState value) {
        if (value == null) {
          throw new NullPointerException();
        }

        alertState_ = value.getNumber();
        onChanged();
            return this;
        }

      /**
       * <code>.floatingquotes.FloatingAverage.AlertState alertState = 10;</code>
       */
      public Builder clearAlertState() {

        alertState_ = 0;
        onChanged();
            return this;
      }

      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:floatingquotes.FloatingAverage)
    }

    // @@protoc_insertion_point(class_scope:floatingquotes.FloatingAverage)
    private static final org.kiwi.proto.FloatingAverageProtos.FloatingAverage DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new org.kiwi.proto.FloatingAverageProtos.FloatingAverage();
    }

    public static org.kiwi.proto.FloatingAverageProtos.FloatingAverage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FloatingAverage>
            PARSER = new com.google.protobuf.AbstractParser<FloatingAverage>() {
      public FloatingAverage parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FloatingAverage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FloatingAverage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FloatingAverage> getParserForType() {
      return PARSER;
    }

      public org.kiwi.proto.FloatingAverageProtos.FloatingAverage getDefaultInstanceForType() {
          return DEFAULT_INSTANCE;
      }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_floatingquotes_Quote_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_floatingquotes_Quote_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_floatingquotes_FloatingAverage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_floatingquotes_FloatingAverage_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
      return descriptor;
    }

  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;

  static {
    java.lang.String[] descriptorData = {
            "\n\013depot.proto\022\016floatingquotes\":\n\005Quote\022\r" +
                    "\n\005value\030\001 \001(\t\022\017\n\007average\030\002 \001(\t\022\021\n\tupdate" +
                    "dAt\030\003 \001(\003\"\303\002\n\017FloatingAverage\022\n\n\002id\030\001 \001(" +
                    "\t\022\014\n\004name\030\002 \001(\t\022\016\n\006symbol\030\003 \001(\t\022\022\n\nmaxDa" +
                    "ysCap\030\004 \001(\005\022%\n\006quotes\030\005 \003(\0132\025.floatingqu" +
                    "otes.Quote\022\032\n\022deviationThreshold\030\006 \001(\t\022\025" +
                    "\n\rlatestAverage\030\007 \001(\t\022\030\n\020latestQuoteValu" +
                    "e\030\010 \001(\t\022\023\n\013closingDate\030\t \001(\003\022>\n\nalertSta" +
                    "te\030\n \001(\0162*.floatingquotes.FloatingAverag" +
                    "e.AlertState\")\n\nAlertState\022\010\n\004NONE\020\000\022\007\n\003",
            "BUY\020\001\022\010\n\004SELL\020\002B\'\n\016org.kiwi.protoB\025Float" +
                    "ingAverageProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_floatingquotes_Quote_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_floatingquotes_Quote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_floatingquotes_Quote_descriptor,
            new java.lang.String[]{"Value", "Average", "UpdatedAt",});
    internal_static_floatingquotes_FloatingAverage_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_floatingquotes_FloatingAverage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_floatingquotes_FloatingAverage_descriptor,
            new java.lang.String[] { "Id", "Name", "Symbol", "MaxDaysCap", "Quotes", "DeviationThreshold", "LatestAverage", "LatestQuoteValue", "ClosingDate", "AlertState", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
